// MyCom.idl: MyCom 的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 生成类型库(MyCom.tlb)和封送处理代码。

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(a817e7a2-43fa-11d0-9e44-00aa00b6770a),
	dual,
	pointer_default(unique)
]
interface IComponentRegistrar : IDispatch
{
	[id(1)]	HRESULT Attach([in] BSTR bstrPath);
	[id(2)]	HRESULT RegisterAll();
	[id(3)]	HRESULT UnregisterAll();
	[id(4)]	HRESULT GetComponents([out] SAFEARRAY(BSTR)* pbstrCLSIDs, [out] SAFEARRAY(BSTR)* pbstrDescriptions);
	[id(5)]	HRESULT RegisterComponent([in] BSTR bstrCLSID);
	[id(6)] HRESULT UnregisterComponent([in] BSTR bstrCLSID);
};

[
	object,
	uuid(10da1059-c1de-4036-84fb-3bae79906069),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IMyClass : IDispatch
{
    [id(1)] HRESULT TotalSum([in] LONG n, [out] LONG* sum);
};
[
	uuid(3cf0adcb-2625-470b-9325-e93da573a0ab),
	version(1.0),
	custom(a817e7a1-43fa-11d0-9e44-00aa00b6770a,"{fa998c86-13ca-42a7-9e46-a8c03973f7ce}")
]
library MyComLib
{
	importlib("stdole2.tlb");
	[
		uuid(fa998c86-13ca-42a7-9e46-a8c03973f7ce)
	]
	coclass CompReg
	{
		[default] interface IComponentRegistrar;
	};
	[
		uuid(f606ffcd-1eee-43ca-b7bb-db3c196e15e1)
	]
	coclass MyClass
	{
		[default] interface IMyClass;
	};
};

import "shobjidl.idl";
