// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: network.proto

#ifndef PROTOBUF_INCLUDED_network_2eproto
#define PROTOBUF_INCLUDED_network_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_network_2eproto 

namespace protobuf_network_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[4];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_network_2eproto
namespace lego {
namespace network {
namespace protobuf {
class GetNetworkNodesRequest;
class GetNetworkNodesRequestDefaultTypeInternal;
extern GetNetworkNodesRequestDefaultTypeInternal _GetNetworkNodesRequest_default_instance_;
class GetNetworkNodesResponse;
class GetNetworkNodesResponseDefaultTypeInternal;
extern GetNetworkNodesResponseDefaultTypeInternal _GetNetworkNodesResponse_default_instance_;
class NetworkMessage;
class NetworkMessageDefaultTypeInternal;
extern NetworkMessageDefaultTypeInternal _NetworkMessage_default_instance_;
class NodeInfo;
class NodeInfoDefaultTypeInternal;
extern NodeInfoDefaultTypeInternal _NodeInfo_default_instance_;
}  // namespace protobuf
}  // namespace network
}  // namespace lego
namespace google {
namespace protobuf {
template<> ::lego::network::protobuf::GetNetworkNodesRequest* Arena::CreateMaybeMessage<::lego::network::protobuf::GetNetworkNodesRequest>(Arena*);
template<> ::lego::network::protobuf::GetNetworkNodesResponse* Arena::CreateMaybeMessage<::lego::network::protobuf::GetNetworkNodesResponse>(Arena*);
template<> ::lego::network::protobuf::NetworkMessage* Arena::CreateMaybeMessage<::lego::network::protobuf::NetworkMessage>(Arena*);
template<> ::lego::network::protobuf::NodeInfo* Arena::CreateMaybeMessage<::lego::network::protobuf::NodeInfo>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace lego {
namespace network {
namespace protobuf {

// ===================================================================

class GetNetworkNodesRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:lego.network.protobuf.GetNetworkNodesRequest) */ {
 public:
  GetNetworkNodesRequest();
  virtual ~GetNetworkNodesRequest();

  GetNetworkNodesRequest(const GetNetworkNodesRequest& from);

  inline GetNetworkNodesRequest& operator=(const GetNetworkNodesRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GetNetworkNodesRequest(GetNetworkNodesRequest&& from) noexcept
    : GetNetworkNodesRequest() {
    *this = ::std::move(from);
  }

  inline GetNetworkNodesRequest& operator=(GetNetworkNodesRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GetNetworkNodesRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GetNetworkNodesRequest* internal_default_instance() {
    return reinterpret_cast<const GetNetworkNodesRequest*>(
               &_GetNetworkNodesRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(GetNetworkNodesRequest* other);
  friend void swap(GetNetworkNodesRequest& a, GetNetworkNodesRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GetNetworkNodesRequest* New() const final {
    return CreateMaybeMessage<GetNetworkNodesRequest>(NULL);
  }

  GetNetworkNodesRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GetNetworkNodesRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GetNetworkNodesRequest& from);
  void MergeFrom(const GetNetworkNodesRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetNetworkNodesRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 net_id = 1;
  bool has_net_id() const;
  void clear_net_id();
  static const int kNetIdFieldNumber = 1;
  ::google::protobuf::uint32 net_id() const;
  void set_net_id(::google::protobuf::uint32 value);

  // optional uint32 count = 2;
  bool has_count() const;
  void clear_count();
  static const int kCountFieldNumber = 2;
  ::google::protobuf::uint32 count() const;
  void set_count(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:lego.network.protobuf.GetNetworkNodesRequest)
 private:
  void set_has_net_id();
  void clear_has_net_id();
  void set_has_count();
  void clear_has_count();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::uint32 net_id_;
  ::google::protobuf::uint32 count_;
  friend struct ::protobuf_network_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class NodeInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:lego.network.protobuf.NodeInfo) */ {
 public:
  NodeInfo();
  virtual ~NodeInfo();

  NodeInfo(const NodeInfo& from);

  inline NodeInfo& operator=(const NodeInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  NodeInfo(NodeInfo&& from) noexcept
    : NodeInfo() {
    *this = ::std::move(from);
  }

  inline NodeInfo& operator=(NodeInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const NodeInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const NodeInfo* internal_default_instance() {
    return reinterpret_cast<const NodeInfo*>(
               &_NodeInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(NodeInfo* other);
  friend void swap(NodeInfo& a, NodeInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline NodeInfo* New() const final {
    return CreateMaybeMessage<NodeInfo>(NULL);
  }

  NodeInfo* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<NodeInfo>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const NodeInfo& from);
  void MergeFrom(const NodeInfo& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NodeInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bytes public_ip = 1;
  bool has_public_ip() const;
  void clear_public_ip();
  static const int kPublicIpFieldNumber = 1;
  const ::std::string& public_ip() const;
  void set_public_ip(const ::std::string& value);
  #if LANG_CXX11
  void set_public_ip(::std::string&& value);
  #endif
  void set_public_ip(const char* value);
  void set_public_ip(const void* value, size_t size);
  ::std::string* mutable_public_ip();
  ::std::string* release_public_ip();
  void set_allocated_public_ip(::std::string* public_ip);

  // optional bytes local_ip = 3;
  bool has_local_ip() const;
  void clear_local_ip();
  static const int kLocalIpFieldNumber = 3;
  const ::std::string& local_ip() const;
  void set_local_ip(const ::std::string& value);
  #if LANG_CXX11
  void set_local_ip(::std::string&& value);
  #endif
  void set_local_ip(const char* value);
  void set_local_ip(const void* value, size_t size);
  ::std::string* mutable_local_ip();
  ::std::string* release_local_ip();
  void set_allocated_local_ip(::std::string* local_ip);

  // optional bytes id = 5;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 5;
  const ::std::string& id() const;
  void set_id(const ::std::string& value);
  #if LANG_CXX11
  void set_id(::std::string&& value);
  #endif
  void set_id(const char* value);
  void set_id(const void* value, size_t size);
  ::std::string* mutable_id();
  ::std::string* release_id();
  void set_allocated_id(::std::string* id);

  // optional bytes dht_key = 7;
  bool has_dht_key() const;
  void clear_dht_key();
  static const int kDhtKeyFieldNumber = 7;
  const ::std::string& dht_key() const;
  void set_dht_key(const ::std::string& value);
  #if LANG_CXX11
  void set_dht_key(::std::string&& value);
  #endif
  void set_dht_key(const char* value);
  void set_dht_key(const void* value, size_t size);
  ::std::string* mutable_dht_key();
  ::std::string* release_dht_key();
  void set_allocated_dht_key(::std::string* dht_key);

  // optional bytes pubkey = 8;
  bool has_pubkey() const;
  void clear_pubkey();
  static const int kPubkeyFieldNumber = 8;
  const ::std::string& pubkey() const;
  void set_pubkey(const ::std::string& value);
  #if LANG_CXX11
  void set_pubkey(::std::string&& value);
  #endif
  void set_pubkey(const char* value);
  void set_pubkey(const void* value, size_t size);
  ::std::string* mutable_pubkey();
  ::std::string* release_pubkey();
  void set_allocated_pubkey(::std::string* pubkey);

  // optional int32 public_port = 2;
  bool has_public_port() const;
  void clear_public_port();
  static const int kPublicPortFieldNumber = 2;
  ::google::protobuf::int32 public_port() const;
  void set_public_port(::google::protobuf::int32 value);

  // optional int32 local_port = 4;
  bool has_local_port() const;
  void clear_local_port();
  static const int kLocalPortFieldNumber = 4;
  ::google::protobuf::int32 local_port() const;
  void set_local_port(::google::protobuf::int32 value);

  // optional int32 nat_type = 6;
  bool has_nat_type() const;
  void clear_nat_type();
  static const int kNatTypeFieldNumber = 6;
  ::google::protobuf::int32 nat_type() const;
  void set_nat_type(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:lego.network.protobuf.NodeInfo)
 private:
  void set_has_public_ip();
  void clear_has_public_ip();
  void set_has_public_port();
  void clear_has_public_port();
  void set_has_local_ip();
  void clear_has_local_ip();
  void set_has_local_port();
  void clear_has_local_port();
  void set_has_id();
  void clear_has_id();
  void set_has_nat_type();
  void clear_has_nat_type();
  void set_has_dht_key();
  void clear_has_dht_key();
  void set_has_pubkey();
  void clear_has_pubkey();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr public_ip_;
  ::google::protobuf::internal::ArenaStringPtr local_ip_;
  ::google::protobuf::internal::ArenaStringPtr id_;
  ::google::protobuf::internal::ArenaStringPtr dht_key_;
  ::google::protobuf::internal::ArenaStringPtr pubkey_;
  ::google::protobuf::int32 public_port_;
  ::google::protobuf::int32 local_port_;
  ::google::protobuf::int32 nat_type_;
  friend struct ::protobuf_network_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GetNetworkNodesResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:lego.network.protobuf.GetNetworkNodesResponse) */ {
 public:
  GetNetworkNodesResponse();
  virtual ~GetNetworkNodesResponse();

  GetNetworkNodesResponse(const GetNetworkNodesResponse& from);

  inline GetNetworkNodesResponse& operator=(const GetNetworkNodesResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GetNetworkNodesResponse(GetNetworkNodesResponse&& from) noexcept
    : GetNetworkNodesResponse() {
    *this = ::std::move(from);
  }

  inline GetNetworkNodesResponse& operator=(GetNetworkNodesResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GetNetworkNodesResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GetNetworkNodesResponse* internal_default_instance() {
    return reinterpret_cast<const GetNetworkNodesResponse*>(
               &_GetNetworkNodesResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(GetNetworkNodesResponse* other);
  friend void swap(GetNetworkNodesResponse& a, GetNetworkNodesResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GetNetworkNodesResponse* New() const final {
    return CreateMaybeMessage<GetNetworkNodesResponse>(NULL);
  }

  GetNetworkNodesResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GetNetworkNodesResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GetNetworkNodesResponse& from);
  void MergeFrom(const GetNetworkNodesResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetNetworkNodesResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .lego.network.protobuf.NodeInfo nodes = 1;
  int nodes_size() const;
  void clear_nodes();
  static const int kNodesFieldNumber = 1;
  ::lego::network::protobuf::NodeInfo* mutable_nodes(int index);
  ::google::protobuf::RepeatedPtrField< ::lego::network::protobuf::NodeInfo >*
      mutable_nodes();
  const ::lego::network::protobuf::NodeInfo& nodes(int index) const;
  ::lego::network::protobuf::NodeInfo* add_nodes();
  const ::google::protobuf::RepeatedPtrField< ::lego::network::protobuf::NodeInfo >&
      nodes() const;

  // @@protoc_insertion_point(class_scope:lego.network.protobuf.GetNetworkNodesResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::lego::network::protobuf::NodeInfo > nodes_;
  friend struct ::protobuf_network_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class NetworkMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:lego.network.protobuf.NetworkMessage) */ {
 public:
  NetworkMessage();
  virtual ~NetworkMessage();

  NetworkMessage(const NetworkMessage& from);

  inline NetworkMessage& operator=(const NetworkMessage& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  NetworkMessage(NetworkMessage&& from) noexcept
    : NetworkMessage() {
    *this = ::std::move(from);
  }

  inline NetworkMessage& operator=(NetworkMessage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const NetworkMessage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const NetworkMessage* internal_default_instance() {
    return reinterpret_cast<const NetworkMessage*>(
               &_NetworkMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(NetworkMessage* other);
  friend void swap(NetworkMessage& a, NetworkMessage& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline NetworkMessage* New() const final {
    return CreateMaybeMessage<NetworkMessage>(NULL);
  }

  NetworkMessage* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<NetworkMessage>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const NetworkMessage& from);
  void MergeFrom(const NetworkMessage& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NetworkMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .lego.network.protobuf.GetNetworkNodesRequest get_net_nodes_req = 1;
  bool has_get_net_nodes_req() const;
  void clear_get_net_nodes_req();
  static const int kGetNetNodesReqFieldNumber = 1;
  private:
  const ::lego::network::protobuf::GetNetworkNodesRequest& _internal_get_net_nodes_req() const;
  public:
  const ::lego::network::protobuf::GetNetworkNodesRequest& get_net_nodes_req() const;
  ::lego::network::protobuf::GetNetworkNodesRequest* release_get_net_nodes_req();
  ::lego::network::protobuf::GetNetworkNodesRequest* mutable_get_net_nodes_req();
  void set_allocated_get_net_nodes_req(::lego::network::protobuf::GetNetworkNodesRequest* get_net_nodes_req);

  // optional .lego.network.protobuf.GetNetworkNodesResponse get_net_nodes_res = 2;
  bool has_get_net_nodes_res() const;
  void clear_get_net_nodes_res();
  static const int kGetNetNodesResFieldNumber = 2;
  private:
  const ::lego::network::protobuf::GetNetworkNodesResponse& _internal_get_net_nodes_res() const;
  public:
  const ::lego::network::protobuf::GetNetworkNodesResponse& get_net_nodes_res() const;
  ::lego::network::protobuf::GetNetworkNodesResponse* release_get_net_nodes_res();
  ::lego::network::protobuf::GetNetworkNodesResponse* mutable_get_net_nodes_res();
  void set_allocated_get_net_nodes_res(::lego::network::protobuf::GetNetworkNodesResponse* get_net_nodes_res);

  // @@protoc_insertion_point(class_scope:lego.network.protobuf.NetworkMessage)
 private:
  void set_has_get_net_nodes_req();
  void clear_has_get_net_nodes_req();
  void set_has_get_net_nodes_res();
  void clear_has_get_net_nodes_res();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::lego::network::protobuf::GetNetworkNodesRequest* get_net_nodes_req_;
  ::lego::network::protobuf::GetNetworkNodesResponse* get_net_nodes_res_;
  friend struct ::protobuf_network_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GetNetworkNodesRequest

// optional uint32 net_id = 1;
inline bool GetNetworkNodesRequest::has_net_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GetNetworkNodesRequest::set_has_net_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GetNetworkNodesRequest::clear_has_net_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GetNetworkNodesRequest::clear_net_id() {
  net_id_ = 0u;
  clear_has_net_id();
}
inline ::google::protobuf::uint32 GetNetworkNodesRequest::net_id() const {
  // @@protoc_insertion_point(field_get:lego.network.protobuf.GetNetworkNodesRequest.net_id)
  return net_id_;
}
inline void GetNetworkNodesRequest::set_net_id(::google::protobuf::uint32 value) {
  set_has_net_id();
  net_id_ = value;
  // @@protoc_insertion_point(field_set:lego.network.protobuf.GetNetworkNodesRequest.net_id)
}

// optional uint32 count = 2;
inline bool GetNetworkNodesRequest::has_count() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void GetNetworkNodesRequest::set_has_count() {
  _has_bits_[0] |= 0x00000002u;
}
inline void GetNetworkNodesRequest::clear_has_count() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void GetNetworkNodesRequest::clear_count() {
  count_ = 0u;
  clear_has_count();
}
inline ::google::protobuf::uint32 GetNetworkNodesRequest::count() const {
  // @@protoc_insertion_point(field_get:lego.network.protobuf.GetNetworkNodesRequest.count)
  return count_;
}
inline void GetNetworkNodesRequest::set_count(::google::protobuf::uint32 value) {
  set_has_count();
  count_ = value;
  // @@protoc_insertion_point(field_set:lego.network.protobuf.GetNetworkNodesRequest.count)
}

// -------------------------------------------------------------------

// NodeInfo

// optional bytes public_ip = 1;
inline bool NodeInfo::has_public_ip() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void NodeInfo::set_has_public_ip() {
  _has_bits_[0] |= 0x00000001u;
}
inline void NodeInfo::clear_has_public_ip() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void NodeInfo::clear_public_ip() {
  public_ip_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_public_ip();
}
inline const ::std::string& NodeInfo::public_ip() const {
  // @@protoc_insertion_point(field_get:lego.network.protobuf.NodeInfo.public_ip)
  return public_ip_.GetNoArena();
}
inline void NodeInfo::set_public_ip(const ::std::string& value) {
  set_has_public_ip();
  public_ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:lego.network.protobuf.NodeInfo.public_ip)
}
#if LANG_CXX11
inline void NodeInfo::set_public_ip(::std::string&& value) {
  set_has_public_ip();
  public_ip_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:lego.network.protobuf.NodeInfo.public_ip)
}
#endif
inline void NodeInfo::set_public_ip(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_public_ip();
  public_ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:lego.network.protobuf.NodeInfo.public_ip)
}
inline void NodeInfo::set_public_ip(const void* value, size_t size) {
  set_has_public_ip();
  public_ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:lego.network.protobuf.NodeInfo.public_ip)
}
inline ::std::string* NodeInfo::mutable_public_ip() {
  set_has_public_ip();
  // @@protoc_insertion_point(field_mutable:lego.network.protobuf.NodeInfo.public_ip)
  return public_ip_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* NodeInfo::release_public_ip() {
  // @@protoc_insertion_point(field_release:lego.network.protobuf.NodeInfo.public_ip)
  if (!has_public_ip()) {
    return NULL;
  }
  clear_has_public_ip();
  return public_ip_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void NodeInfo::set_allocated_public_ip(::std::string* public_ip) {
  if (public_ip != NULL) {
    set_has_public_ip();
  } else {
    clear_has_public_ip();
  }
  public_ip_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), public_ip);
  // @@protoc_insertion_point(field_set_allocated:lego.network.protobuf.NodeInfo.public_ip)
}

// optional int32 public_port = 2;
inline bool NodeInfo::has_public_port() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void NodeInfo::set_has_public_port() {
  _has_bits_[0] |= 0x00000020u;
}
inline void NodeInfo::clear_has_public_port() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void NodeInfo::clear_public_port() {
  public_port_ = 0;
  clear_has_public_port();
}
inline ::google::protobuf::int32 NodeInfo::public_port() const {
  // @@protoc_insertion_point(field_get:lego.network.protobuf.NodeInfo.public_port)
  return public_port_;
}
inline void NodeInfo::set_public_port(::google::protobuf::int32 value) {
  set_has_public_port();
  public_port_ = value;
  // @@protoc_insertion_point(field_set:lego.network.protobuf.NodeInfo.public_port)
}

// optional bytes local_ip = 3;
inline bool NodeInfo::has_local_ip() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void NodeInfo::set_has_local_ip() {
  _has_bits_[0] |= 0x00000002u;
}
inline void NodeInfo::clear_has_local_ip() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void NodeInfo::clear_local_ip() {
  local_ip_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_local_ip();
}
inline const ::std::string& NodeInfo::local_ip() const {
  // @@protoc_insertion_point(field_get:lego.network.protobuf.NodeInfo.local_ip)
  return local_ip_.GetNoArena();
}
inline void NodeInfo::set_local_ip(const ::std::string& value) {
  set_has_local_ip();
  local_ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:lego.network.protobuf.NodeInfo.local_ip)
}
#if LANG_CXX11
inline void NodeInfo::set_local_ip(::std::string&& value) {
  set_has_local_ip();
  local_ip_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:lego.network.protobuf.NodeInfo.local_ip)
}
#endif
inline void NodeInfo::set_local_ip(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_local_ip();
  local_ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:lego.network.protobuf.NodeInfo.local_ip)
}
inline void NodeInfo::set_local_ip(const void* value, size_t size) {
  set_has_local_ip();
  local_ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:lego.network.protobuf.NodeInfo.local_ip)
}
inline ::std::string* NodeInfo::mutable_local_ip() {
  set_has_local_ip();
  // @@protoc_insertion_point(field_mutable:lego.network.protobuf.NodeInfo.local_ip)
  return local_ip_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* NodeInfo::release_local_ip() {
  // @@protoc_insertion_point(field_release:lego.network.protobuf.NodeInfo.local_ip)
  if (!has_local_ip()) {
    return NULL;
  }
  clear_has_local_ip();
  return local_ip_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void NodeInfo::set_allocated_local_ip(::std::string* local_ip) {
  if (local_ip != NULL) {
    set_has_local_ip();
  } else {
    clear_has_local_ip();
  }
  local_ip_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), local_ip);
  // @@protoc_insertion_point(field_set_allocated:lego.network.protobuf.NodeInfo.local_ip)
}

// optional int32 local_port = 4;
inline bool NodeInfo::has_local_port() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void NodeInfo::set_has_local_port() {
  _has_bits_[0] |= 0x00000040u;
}
inline void NodeInfo::clear_has_local_port() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void NodeInfo::clear_local_port() {
  local_port_ = 0;
  clear_has_local_port();
}
inline ::google::protobuf::int32 NodeInfo::local_port() const {
  // @@protoc_insertion_point(field_get:lego.network.protobuf.NodeInfo.local_port)
  return local_port_;
}
inline void NodeInfo::set_local_port(::google::protobuf::int32 value) {
  set_has_local_port();
  local_port_ = value;
  // @@protoc_insertion_point(field_set:lego.network.protobuf.NodeInfo.local_port)
}

// optional bytes id = 5;
inline bool NodeInfo::has_id() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void NodeInfo::set_has_id() {
  _has_bits_[0] |= 0x00000004u;
}
inline void NodeInfo::clear_has_id() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void NodeInfo::clear_id() {
  id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_id();
}
inline const ::std::string& NodeInfo::id() const {
  // @@protoc_insertion_point(field_get:lego.network.protobuf.NodeInfo.id)
  return id_.GetNoArena();
}
inline void NodeInfo::set_id(const ::std::string& value) {
  set_has_id();
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:lego.network.protobuf.NodeInfo.id)
}
#if LANG_CXX11
inline void NodeInfo::set_id(::std::string&& value) {
  set_has_id();
  id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:lego.network.protobuf.NodeInfo.id)
}
#endif
inline void NodeInfo::set_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_id();
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:lego.network.protobuf.NodeInfo.id)
}
inline void NodeInfo::set_id(const void* value, size_t size) {
  set_has_id();
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:lego.network.protobuf.NodeInfo.id)
}
inline ::std::string* NodeInfo::mutable_id() {
  set_has_id();
  // @@protoc_insertion_point(field_mutable:lego.network.protobuf.NodeInfo.id)
  return id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* NodeInfo::release_id() {
  // @@protoc_insertion_point(field_release:lego.network.protobuf.NodeInfo.id)
  if (!has_id()) {
    return NULL;
  }
  clear_has_id();
  return id_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void NodeInfo::set_allocated_id(::std::string* id) {
  if (id != NULL) {
    set_has_id();
  } else {
    clear_has_id();
  }
  id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), id);
  // @@protoc_insertion_point(field_set_allocated:lego.network.protobuf.NodeInfo.id)
}

// optional int32 nat_type = 6;
inline bool NodeInfo::has_nat_type() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void NodeInfo::set_has_nat_type() {
  _has_bits_[0] |= 0x00000080u;
}
inline void NodeInfo::clear_has_nat_type() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void NodeInfo::clear_nat_type() {
  nat_type_ = 0;
  clear_has_nat_type();
}
inline ::google::protobuf::int32 NodeInfo::nat_type() const {
  // @@protoc_insertion_point(field_get:lego.network.protobuf.NodeInfo.nat_type)
  return nat_type_;
}
inline void NodeInfo::set_nat_type(::google::protobuf::int32 value) {
  set_has_nat_type();
  nat_type_ = value;
  // @@protoc_insertion_point(field_set:lego.network.protobuf.NodeInfo.nat_type)
}

// optional bytes dht_key = 7;
inline bool NodeInfo::has_dht_key() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void NodeInfo::set_has_dht_key() {
  _has_bits_[0] |= 0x00000008u;
}
inline void NodeInfo::clear_has_dht_key() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void NodeInfo::clear_dht_key() {
  dht_key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_dht_key();
}
inline const ::std::string& NodeInfo::dht_key() const {
  // @@protoc_insertion_point(field_get:lego.network.protobuf.NodeInfo.dht_key)
  return dht_key_.GetNoArena();
}
inline void NodeInfo::set_dht_key(const ::std::string& value) {
  set_has_dht_key();
  dht_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:lego.network.protobuf.NodeInfo.dht_key)
}
#if LANG_CXX11
inline void NodeInfo::set_dht_key(::std::string&& value) {
  set_has_dht_key();
  dht_key_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:lego.network.protobuf.NodeInfo.dht_key)
}
#endif
inline void NodeInfo::set_dht_key(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_dht_key();
  dht_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:lego.network.protobuf.NodeInfo.dht_key)
}
inline void NodeInfo::set_dht_key(const void* value, size_t size) {
  set_has_dht_key();
  dht_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:lego.network.protobuf.NodeInfo.dht_key)
}
inline ::std::string* NodeInfo::mutable_dht_key() {
  set_has_dht_key();
  // @@protoc_insertion_point(field_mutable:lego.network.protobuf.NodeInfo.dht_key)
  return dht_key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* NodeInfo::release_dht_key() {
  // @@protoc_insertion_point(field_release:lego.network.protobuf.NodeInfo.dht_key)
  if (!has_dht_key()) {
    return NULL;
  }
  clear_has_dht_key();
  return dht_key_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void NodeInfo::set_allocated_dht_key(::std::string* dht_key) {
  if (dht_key != NULL) {
    set_has_dht_key();
  } else {
    clear_has_dht_key();
  }
  dht_key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), dht_key);
  // @@protoc_insertion_point(field_set_allocated:lego.network.protobuf.NodeInfo.dht_key)
}

// optional bytes pubkey = 8;
inline bool NodeInfo::has_pubkey() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void NodeInfo::set_has_pubkey() {
  _has_bits_[0] |= 0x00000010u;
}
inline void NodeInfo::clear_has_pubkey() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void NodeInfo::clear_pubkey() {
  pubkey_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_pubkey();
}
inline const ::std::string& NodeInfo::pubkey() const {
  // @@protoc_insertion_point(field_get:lego.network.protobuf.NodeInfo.pubkey)
  return pubkey_.GetNoArena();
}
inline void NodeInfo::set_pubkey(const ::std::string& value) {
  set_has_pubkey();
  pubkey_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:lego.network.protobuf.NodeInfo.pubkey)
}
#if LANG_CXX11
inline void NodeInfo::set_pubkey(::std::string&& value) {
  set_has_pubkey();
  pubkey_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:lego.network.protobuf.NodeInfo.pubkey)
}
#endif
inline void NodeInfo::set_pubkey(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_pubkey();
  pubkey_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:lego.network.protobuf.NodeInfo.pubkey)
}
inline void NodeInfo::set_pubkey(const void* value, size_t size) {
  set_has_pubkey();
  pubkey_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:lego.network.protobuf.NodeInfo.pubkey)
}
inline ::std::string* NodeInfo::mutable_pubkey() {
  set_has_pubkey();
  // @@protoc_insertion_point(field_mutable:lego.network.protobuf.NodeInfo.pubkey)
  return pubkey_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* NodeInfo::release_pubkey() {
  // @@protoc_insertion_point(field_release:lego.network.protobuf.NodeInfo.pubkey)
  if (!has_pubkey()) {
    return NULL;
  }
  clear_has_pubkey();
  return pubkey_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void NodeInfo::set_allocated_pubkey(::std::string* pubkey) {
  if (pubkey != NULL) {
    set_has_pubkey();
  } else {
    clear_has_pubkey();
  }
  pubkey_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), pubkey);
  // @@protoc_insertion_point(field_set_allocated:lego.network.protobuf.NodeInfo.pubkey)
}

// -------------------------------------------------------------------

// GetNetworkNodesResponse

// repeated .lego.network.protobuf.NodeInfo nodes = 1;
inline int GetNetworkNodesResponse::nodes_size() const {
  return nodes_.size();
}
inline void GetNetworkNodesResponse::clear_nodes() {
  nodes_.Clear();
}
inline ::lego::network::protobuf::NodeInfo* GetNetworkNodesResponse::mutable_nodes(int index) {
  // @@protoc_insertion_point(field_mutable:lego.network.protobuf.GetNetworkNodesResponse.nodes)
  return nodes_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::lego::network::protobuf::NodeInfo >*
GetNetworkNodesResponse::mutable_nodes() {
  // @@protoc_insertion_point(field_mutable_list:lego.network.protobuf.GetNetworkNodesResponse.nodes)
  return &nodes_;
}
inline const ::lego::network::protobuf::NodeInfo& GetNetworkNodesResponse::nodes(int index) const {
  // @@protoc_insertion_point(field_get:lego.network.protobuf.GetNetworkNodesResponse.nodes)
  return nodes_.Get(index);
}
inline ::lego::network::protobuf::NodeInfo* GetNetworkNodesResponse::add_nodes() {
  // @@protoc_insertion_point(field_add:lego.network.protobuf.GetNetworkNodesResponse.nodes)
  return nodes_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::lego::network::protobuf::NodeInfo >&
GetNetworkNodesResponse::nodes() const {
  // @@protoc_insertion_point(field_list:lego.network.protobuf.GetNetworkNodesResponse.nodes)
  return nodes_;
}

// -------------------------------------------------------------------

// NetworkMessage

// optional .lego.network.protobuf.GetNetworkNodesRequest get_net_nodes_req = 1;
inline bool NetworkMessage::has_get_net_nodes_req() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void NetworkMessage::set_has_get_net_nodes_req() {
  _has_bits_[0] |= 0x00000001u;
}
inline void NetworkMessage::clear_has_get_net_nodes_req() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void NetworkMessage::clear_get_net_nodes_req() {
  if (get_net_nodes_req_ != NULL) get_net_nodes_req_->Clear();
  clear_has_get_net_nodes_req();
}
inline const ::lego::network::protobuf::GetNetworkNodesRequest& NetworkMessage::_internal_get_net_nodes_req() const {
  return *get_net_nodes_req_;
}
inline const ::lego::network::protobuf::GetNetworkNodesRequest& NetworkMessage::get_net_nodes_req() const {
  const ::lego::network::protobuf::GetNetworkNodesRequest* p = get_net_nodes_req_;
  // @@protoc_insertion_point(field_get:lego.network.protobuf.NetworkMessage.get_net_nodes_req)
  return p != NULL ? *p : *reinterpret_cast<const ::lego::network::protobuf::GetNetworkNodesRequest*>(
      &::lego::network::protobuf::_GetNetworkNodesRequest_default_instance_);
}
inline ::lego::network::protobuf::GetNetworkNodesRequest* NetworkMessage::release_get_net_nodes_req() {
  // @@protoc_insertion_point(field_release:lego.network.protobuf.NetworkMessage.get_net_nodes_req)
  clear_has_get_net_nodes_req();
  ::lego::network::protobuf::GetNetworkNodesRequest* temp = get_net_nodes_req_;
  get_net_nodes_req_ = NULL;
  return temp;
}
inline ::lego::network::protobuf::GetNetworkNodesRequest* NetworkMessage::mutable_get_net_nodes_req() {
  set_has_get_net_nodes_req();
  if (get_net_nodes_req_ == NULL) {
    auto* p = CreateMaybeMessage<::lego::network::protobuf::GetNetworkNodesRequest>(GetArenaNoVirtual());
    get_net_nodes_req_ = p;
  }
  // @@protoc_insertion_point(field_mutable:lego.network.protobuf.NetworkMessage.get_net_nodes_req)
  return get_net_nodes_req_;
}
inline void NetworkMessage::set_allocated_get_net_nodes_req(::lego::network::protobuf::GetNetworkNodesRequest* get_net_nodes_req) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete get_net_nodes_req_;
  }
  if (get_net_nodes_req) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      get_net_nodes_req = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, get_net_nodes_req, submessage_arena);
    }
    set_has_get_net_nodes_req();
  } else {
    clear_has_get_net_nodes_req();
  }
  get_net_nodes_req_ = get_net_nodes_req;
  // @@protoc_insertion_point(field_set_allocated:lego.network.protobuf.NetworkMessage.get_net_nodes_req)
}

// optional .lego.network.protobuf.GetNetworkNodesResponse get_net_nodes_res = 2;
inline bool NetworkMessage::has_get_net_nodes_res() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void NetworkMessage::set_has_get_net_nodes_res() {
  _has_bits_[0] |= 0x00000002u;
}
inline void NetworkMessage::clear_has_get_net_nodes_res() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void NetworkMessage::clear_get_net_nodes_res() {
  if (get_net_nodes_res_ != NULL) get_net_nodes_res_->Clear();
  clear_has_get_net_nodes_res();
}
inline const ::lego::network::protobuf::GetNetworkNodesResponse& NetworkMessage::_internal_get_net_nodes_res() const {
  return *get_net_nodes_res_;
}
inline const ::lego::network::protobuf::GetNetworkNodesResponse& NetworkMessage::get_net_nodes_res() const {
  const ::lego::network::protobuf::GetNetworkNodesResponse* p = get_net_nodes_res_;
  // @@protoc_insertion_point(field_get:lego.network.protobuf.NetworkMessage.get_net_nodes_res)
  return p != NULL ? *p : *reinterpret_cast<const ::lego::network::protobuf::GetNetworkNodesResponse*>(
      &::lego::network::protobuf::_GetNetworkNodesResponse_default_instance_);
}
inline ::lego::network::protobuf::GetNetworkNodesResponse* NetworkMessage::release_get_net_nodes_res() {
  // @@protoc_insertion_point(field_release:lego.network.protobuf.NetworkMessage.get_net_nodes_res)
  clear_has_get_net_nodes_res();
  ::lego::network::protobuf::GetNetworkNodesResponse* temp = get_net_nodes_res_;
  get_net_nodes_res_ = NULL;
  return temp;
}
inline ::lego::network::protobuf::GetNetworkNodesResponse* NetworkMessage::mutable_get_net_nodes_res() {
  set_has_get_net_nodes_res();
  if (get_net_nodes_res_ == NULL) {
    auto* p = CreateMaybeMessage<::lego::network::protobuf::GetNetworkNodesResponse>(GetArenaNoVirtual());
    get_net_nodes_res_ = p;
  }
  // @@protoc_insertion_point(field_mutable:lego.network.protobuf.NetworkMessage.get_net_nodes_res)
  return get_net_nodes_res_;
}
inline void NetworkMessage::set_allocated_get_net_nodes_res(::lego::network::protobuf::GetNetworkNodesResponse* get_net_nodes_res) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete get_net_nodes_res_;
  }
  if (get_net_nodes_res) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      get_net_nodes_res = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, get_net_nodes_res, submessage_arena);
    }
    set_has_get_net_nodes_res();
  } else {
    clear_has_get_net_nodes_res();
  }
  get_net_nodes_res_ = get_net_nodes_res;
  // @@protoc_insertion_point(field_set_allocated:lego.network.protobuf.NetworkMessage.get_net_nodes_res)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace network
}  // namespace lego

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_network_2eproto
